// sign up dialog step numbers

const FIRST_SIGNUP_STEP_NUMBER = 1;
const NUM_OF_SIGNUP_STEPS = 3;

const CHARACTER_LIMIT = 280;

const VALIDATION_DELAY = 800;

export {
  CHARACTER_LIMIT,
  FIRST_SIGNUP_STEP_NUMBER,
  NUM_OF_SIGNUP_STEPS,
  VALIDATION_DELAY,
};
