const CHARACTER_LIMIT = 280;
const FIRST_STEP = 1;
const NUM_OF_SIGNUP_STEPS = 6;
const PASSWORD_STEP = 3;
const VALIDATION_DELAY = 800;

export {
  CHARACTER_LIMIT,
  FIRST_STEP,
  NUM_OF_SIGNUP_STEPS,
  PASSWORD_STEP,
  VALIDATION_DELAY,
};
