const ERROR_COLOR = "text-[#f1202d]";
const PRIMARY_COLOR = "text-[#1e9bf0]";

const DARK_TEXT_COLOR = "dark:text-[#71767b]";
const DARK_INPUT_FIELD_BORDER_COLOR = "#333639";
const DARK_BORDER_COLOR = "#536471";
const DARK_HOVER_BG_COLOR = "#eff3f4";

export {
  ERROR_COLOR,
  PRIMARY_COLOR,
  DARK_TEXT_COLOR,
  DARK_INPUT_FIELD_BORDER_COLOR,
  DARK_BORDER_COLOR,
  DARK_HOVER_BG_COLOR,
};
